### ISSUE TITLE
Ellipses and LOBs disappear when the origin is out of sight in 2D mode

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#107]
In 2D mode, when I draw an ellipse or lob, and zoom in far enough so that I can see part of the ellipse or line but not the origin of a feature, the ellipse/line disappears.

@wallw-bits pointed out this could be tied to forEachFeatureIntersectingExtent in vector.js which does an intersection test with feature.getGeometry

**Comment by wallw-bits** [comment]
That's not _quite_ what I said.

If the geometry changes on a feature, that feature needs to be removed and re-indexed in the underlying r-tree. So, either `feature.setGeometry()` does not cause that (which might be an OpenLayers problem) or we are changing the geometry function on the feature rather than calling `feature.setGeometry()`, which produces the unindexed geometry.

The way you check if a feature/geometry is in the r-tree:
```
source.forEachFeatureInExtent(extent, function(feature) {
  if (feature === featureToCheck) {
    console.log('found it!');
  }
});
```

**Comment by wallw-bits** [comment]
I was going off the top of my head with the last post. I'm not actually able to recreate the issue with ellipses.

@welchyd, can you please provide info to reproduce?

**Comment by jsalankey** [comment]
I was seeing it constantly with the line styling stuff @welchyd has been working on, so it's likely related to geometry styles not being indexed in the r-tree. I don't know if that's considered an OL bug (probably not) or if it's something we'll need to refactor to fix.

**Comment by wallw-bits** [comment]
Makes perfect sense. I was just curiously not getting it when I went to actually test it.
