### ISSUE TITLE
2D map renders in the background while in 3D mode

### ISSUE THREAD

**Issue by jsalankey** [ngageoint/opensphere#129]
Something in the recent updates to OL/Cesium/OLCS likely changed how we disabled the rendering of OL while in the Cesium view. It's easy to see when you have ~10k features loaded, Cesium rendering will be significantly slowed and a huge portion of the CPU trace will be OL's rendering stack.

**Comment by bradh** [comment]
Do you know which of the upgrades (4.4 to 4.6.2; or 4.6.2 to 4.6.4) caused the breakage?

**Comment by schmidtk** [comment]
I'm going to guess 4.4 to 4.6.2 because the others were bug fixes. Openlayers must have made a change that caused a hidden root group to still render its children, because in the past `ol-cesium` disabled rendering by [hiding the root group](https://github.com/openlayers/ol-cesium/pull/66/files). I'm looking into it.

**Comment by bradh** [comment]
Thanks. I probably won't be able to dig into it until the weekend.

**Comment by schmidtk** [comment]
Tracked it down. [This mixin](https://github.com/ngageoint/opensphere/blob/master/src/os/mixin/layerbasemixin.js#L22) was added to fix attributions not displaying in 3D mode, and had the side effect of rendering the 2D vector canvas while 3D mode was active. We'll have to revert that change and find another way to display attributions for 3D mode.
