### ISSUE TITLE
Improve Cesium multi-geometry translation

### ISSUE THREAD

**Issue by schmidtk** [ngageoint/opensphere#135]
Functions like `ol.geom.MultiLineString#getLineStrings` and `ol.geom.MultiPolygon#getPolygons` reconstitute the sub geometries from flat coordinates on each call. Since new geometries are created each time, the Cesium feature converter dumps the old primitive(s) representing the multi geometry and creates new ones. This happens on every change to the feature, including style changes, and is very expensive. We should determine a better approach to synchronizing multi geometries that promotes reuse of Cesium primitives.

It would be ideal to avoid calling `getLineStrings`, etc, and instead using the flat coordinates, stride, and ends to create Cesium primitives. This would avoid creating unnecessary Openlayers objects that are going to be immediately GC'ed.

Consider track animation while working this. MultiTracks and tracks crossing the date line are split into a MultiLineString, and while animating they may show `0..n` of the sub-geos.

**Comment by wallw-bits** [comment]
Are you also concerned about Array creation in those? If not, a happy medium might be to call `getCoordinates()` rather than `getLineStrings()` or `getPolygons()`, as those call into the proper `ol.geom.flat.inflate.coordinatesX()` method. That's what we're doing in `os.interpolate`, but that file also intends to change the coordinates array rather than simply read it.

**Comment by schmidtk** [comment]
The update will happen on each timeline frame while animating tracks, so I'd prefer to use the flat coordinates directly to avoid as much unnecessary GC as possible.
