### ISSUE TITLE
Unexpected nodes in layer tree (KML)

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#163]
[Originally from review of #136, but actually occurs without that change].

With https://raw.githubusercontent.com/mapbox/togeojson/master/test/data/multitrack.kml I see some UI artifacts that look like styles and Document properties being interpreted as features. I would expect to see the tour and the two placemarks, but not the other leaf elements in the tree.

![image](https://user-images.githubusercontent.com/174642/36821265-24582642-1d46-11e8-9bd6-5a7686bb7b4b.png)

**Comment by bradh** [comment]
Interestingly, doesn't occur in the debug app. 

The test is a regular expression, which looks like
`/^NetworkLink|Placemark|GroundOverlay|ScreenOverlay|Tour|$/`

That last part is caused by a schema with no name.
```
<Schema id="schema">
<gx:SimpleArrayField name="power" type="int">
<displayName><![CDATA[Power (W)]]></displayName>
</gx:SimpleArrayField>
<gx:SimpleArrayField name="cadence" type="int">
<displayName><![CDATA[Cadence (rpm)]]></displayName>
</gx:SimpleArrayField>
<gx:SimpleArrayField name="heart_rate" type="int">
<displayName><![CDATA[Heart rate (bpm)]]></displayName>
</gx:SimpleArrayField>
</Schema>
```

Now it gets more difficult. 

The google docs (https://developers.google.com/kml/documentation/kmlreference#schema) say that name is required - the schema field is ignored if not present.

However that does not appear in OGC KML 2.2 spec (07-147r2, section 9.8) or the OGC [KML 2.3 spec](http://docs.opengeospatial.org/is/12-007r2/12-007r2.html#203).

Its not clear to me whether we should even be using the `name` attribute here. I'm only familiar with schema-defined elements being nested inside `ExtendedData`. Is there a data format we need to support here that does require this?

**Comment by bradh** [comment]
Urgh: https://github.com/google/libkml/blob/master/src/kml/engine/parse_old_schema.cc#L62

**Comment by schmidtk** [comment]
The `name` attribute shouldn't be required. That allows you to create elements like `MyCustomPlacemark` that are parsed as a Placemark, but use the provided schema for their ExtendedData. You can also use a normal Placemark with ExtendedData that references the schema in a `<SchemaData schemaUrl=“#schema”>` element, though our parser does not fully support that. OpenLayers sort of reads them, but interprets every value as a string instead of using the defined types.

We also don't support `gx:SimpleArrayField` or the 2.3 spec version, which is another enhancement we may want to look into in the future. That's used to provide per-coordinate metadata for tracks, which OpenSphere doesn't have a way to visualize right now.
