### ISSUE TITLE
KML Network link shows "cannot be parsed" error 

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#22]
Trying with `http://www.nhc.noaa.gov/gis/kml/nhc_active.kml` (see http://www.nhc.noaa.gov/gis/activekml.php). 

The UI error is `Unable to load URL "http://www.nhc.noaa.gov/gis/kml/nhc_active.kml"! Please check that it was entered correctly.`

The real issue appears to be CORS:
```
log:GET http://www.nhc.noaa.gov/gis/kml/nhc_active.kml
log:Http response at 400 or 500 level. Http Status code: 0
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.nhc.noaa.gov/gis/kml/nhc_active.kml. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Editing to add `Access-Control-Allow-Origin: *` and resending appears to work OK.

**Comment by wallw-bits** [comment]
In general, CORS must enabled by remote servers or requests will not work.

However, as part of its request stack, OpenSphere includes the `ProxyHandler` class, which attempts to proxy the requests through the proxy configured in `config/settings.json` at `admin.proxy` (which can be overridden by plugin, application, or deployment configs). If the CORS-enabled requests fail, the request will be tried through the proxy. While this is not ideal (it takes twice as many requests to get responses), it results in a nicer experience for users because it works a little more often. It is also useful when OpenSphere is deployed via https, and servers on http would be blocked by the browser due to mixed content.

Now that I'm looking at it, the proxy probably should not be enabled by default.

**Comment by bradh** [comment]
Not arguing the CORS part, but its still a less-than-desirable user experience in the default App.

**Comment by wallw-bits** [comment]
Well (and I should probably write this up somewhere more official), OpenSphere is not intended to be built and run locally to the machine by users, but rather deployed to a server by a sysadmin. Given a proper setup guide (which we admittedly do not have yet), they should be able to either set up their own proxy, point at something like [cors-anywhere](https://cors-anywhere.herokuapp.com/) by setting `admin.proxy.url` to `https://cors-anywhere.herokuapp.com/{url}`.

Developers can implement the `/proxy/` endpoint (couple of lines in nginx/httpd config), or point it elsewhere. However, one should probably be careful implementing arbitrary proxies in production.

Users running locally to the machine would be much better served if we deployed it with [electron](https://electronjs.org/), as that would eliminate the need for CORS in the first place (but would require a couple of minor code changes to get working).
