### ISSUE TITLE
Remove support for Cesium.CesiumTerrainProvider

### ISSUE THREAD

**Issue by schmidtk** [ngageoint/opensphere#229]
`CesiumTerrainProvider` is going away ([source](https://cesium.com/blog/2018/03/01/introducing-cesium-world-terrain/)) so we should remove it from OpenSphere. It was deprecated in 1.43 (#227) and will be officially dropped on September 1, 2018.

We should also look into supporting Cesium World Terrain, which will be free to use until September 1 then will require a [Cesium ion](https://cesium.com/blog/2018/03/01/hello-cesium-ion/) account key to use. We should add support for configuring this account key, so we can enable this terrain type in application deployments.

**Comment by bradh** [comment]
On review, it looks like the data source is going away, so we should change the default.

We may want to keep the provider UI because it is potentially usable with non-AGI sources (like https://github.com/geo-data/cesium-terrain-server).

**Comment by wallw-bits** [comment]
I think what Kevin is saying is that since it is being removed from Cesium itself, an upgrade to a Cesium version which lacks that functionality will render our (tiny) wrapper useless. Might be better to try and convince Cesium to leave it in (noting that there are several other terrain data servers which serve that format besides AGI's). A more complex option would be to pull that functionality from Cesium and maintain it in OpenSphere.

This is different from the mapzen/pelias case because that particular functionality was all maintained within OpenSphere. For terrain, the implementation is almost entirely in Cesium. We just have some stuff that configures it.
