### ISSUE TITLE
Places have interesting altitudes

### ISSUE THREAD

**Issue by csgibson** [ngageoint/opensphere#381]
Possibly related to #183 

Point places that are created by the user through context menu have a random value as altitude.

**Comment by schmidtk** [comment]
`getCoordinateFromPixel` was modified in the Cesium renderer to pick the globe instead of the ellipsoid:
https://github.com/ngageoint/opensphere/blob/22764a6722ba2b320d00f45919595be1982bf4e2/src/plugin/cesium/cesiumrenderer.js#L238-L243

When terrain is enabled, this creates the saved place on the terrain where the user right-clicked, instead of a coordinate "through" the terrain on the surface of the ellipsoid. This was especially noticeable when viewing mountains at an angle. Creating a saved place in a mountainous region could put the coordinate very far from the clicked target.

This does not work well with the default terrain provider (`Cesium.EllipsoidTerrainProvider`), and the altitude you're seeing is likely the difference between the Earth's max radius and the radius of the ellipsoid where the user clicked.

We should fix this by zeroing out altitude in `getCoordinateFromPixel` when terrain is disabled.

**Comment by swtyler** [comment]
Places now have a far less interesting value of 0 when created. I believe this can be closed via https://github.com/ngageoint/opensphere/commit/4ca67c4286e0b668906e7a0dad71012fed12e0fd unless we want to do something more with terrain.

**Comment by schmidtk** [comment]
Further work will require support from Cesium for a non-hacky solution, so I'm fine with closing this.
