### ISSUE TITLE
Leading zeros on lat/long

### ISSUE THREAD

**Issue by smithtb** [ngageoint/opensphere#471]
Opensphere does not plot DMS coordinates correctly if there is not a leading zero. For example, if you search for the coordinate 380516N 25360W, it gives a different location than 380516N 025360W gives.

**Comment by wallw-bits** [comment]
This case is valid per https://en.wikipedia.org/wiki/ISO_6709 and one of us forgot to put in a test for it because that used to work.

We should be parsing the Machine, Human, and String representations covered in that spec.

**Comment by wallw-bits** [comment]
I spoke too soon. `25360W` is a valid DMM longitude (254deg 0min 0sec) according to the spec, but not a valid DMS longitude (not enough digits, the spec does require leading zeroes. See the Eiffel Tower example: `+48.8577+002.295/`). `380516N` is a valid DMS latitude, but not a DMM latitude.

Because these aren't the same ("DMS" for latitude and "DMM" for longitude), neither our main DMS nor DMM regexes pick it up and it is instead being parsed by something fuzzier which should be fixable even though it is outside the spec.

**Comment by csgibson** [comment]
The actual coordinate causing the issue was 334600N 25500E
