### ISSUE TITLE
Quick add places

### ISSUE THREAD

**Issue by csgibson** [ngageoint/opensphere#476]
Users would like the ability to quickly add places to the map. We can do this in opensphere or a plugin (thoughts @wallw-bits @schmidtk?). 

They are looking for something like this:
1. Map context menu
2. Quick add place
3. Name it something (e.g. "Park") or default
4. Hit a hotkey with the mouse over another location to add "Park 2", "Park 3" ...
5. Different hotkey (or same right click option) to start a new count of something else (e.g. "School")
6. Hotkey to add more

**Comment by wallw-bits** [comment]
You can do that entirely in a new plugin without needing to add anything to the `places` plugin.

**Comment by schmidtk** [comment]
I would consider an alternate interaction for selecting multiple positions. The Quick Add Places form could be the same as the normal one, with the following changes:

- The Position control still hides the window, but allows you to click as many positions as you want until you hit Enter/Esc. You could also display a small "Done" window so it's very obvious how the user finishes adding positions.
- When finished, a scrollable list of positions are displayed to the user in the form.
- Hovering a position should highlight the marker on the map, and each position should be individually removable in case they made a mistake.
- Clicking OK saves one place per position, using the one-up naming you described.

Hotkeys are generally more awkward to use/discover vs just clicking the map to add a new position, and you want a clear way to get out of the "add positions" state to avoid confusion.

**Comment by schmidtk** [comment]
Another idea that avoids worrying about a big nasty list of positions in the form (because places are very easy to remove directly from the layer):

- The base form doesn't have a Position control at all, but has all of the other controls (maybe not Annotations).
- When you click OK (probably named something else), you can start clicking the map to add positions with the settings you defined in the form. Every click saves a place to the layer using the one-up naming.
- The "Done" window has two buttons, one to reopen the form to change the name and create more places, one to finish quick add.

**Comment by bradh** [comment]
Was this (partly?) resolved by https://github.com/ngageoint/opensphere/commit/e6ede62b28d47d7c98b16975c55632cc12141b45 ?

**Comment by schmidtk** [comment]
Yes it was. The initial capability described in this issue is complete, and any further enhancements can be written up separately if needed.
