### ISSUE TITLE
osasm.toMGRS throws an exception on latitudes > 90 or < -90

### ISSUE THREAD

**Issue by jsalankey** [ngageoint/opensphere#479]
Obviously data should never have non-normalized latitudes, but in the event that it does, our parsing breaks in `os.feature.populateCoordFields` when trying to do the MGRS conversion. We either need to normalize it before passing it to that function, cap it to 90 or -90, or some other option that prevents us from failing to parse the full set of features being added to a source.

**Comment by schmidtk** [comment]
I'm going to fix this in `osasm.toMGRS` by returning `INVALID` instead of throwing an error (https://github.com/ngageoint/opensphere-asm/pull/1). `osasm.toLonLat` will still throw if the MGRS string is not valid, but I'll document this in the externs and make sure the exception is handled properly in OpenSphere.

We could detect invalid MGRS in osasm with a regular expression, but we would have to ensure it exactly matches valid strings. `os.geo.MGRS_REGEXP` will match invalid strings because it doesn't account for omissions in the grid zone lettering.

**Comment by schmidtk** [comment]
This is fixed with `opensphere-asm@1.1.0`.
