### ISSUE TITLE
Provide API and plugin example for feed-based data source

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#60]
There are many data sources that are near-real-time feeds (so you can't just open the file / download the data at initialisation). Instead, the data is "drip" (or firehose...) fed, often with updates to previous position information for an entity.

Examples are ship locations over AIS, aircraft locations from ADS-B, other formats converted into Cursor-on-Target, GPS "puck" locations in NMEA-0183, or tracking information for one or more UAVs. All of those are potentially useful data sources in an OS app.

It would be useful if there was OS API to define an interface for such plugins to implement, an example plugin to copy from, and support on the OS side to integrate those plugins.

**Comment by wallw-bits** [comment]
We have two options for streams: 

* [`os.net.LongPoll`](https://github.com/ngageoint/opensphere/blob/master/src/os/net/longpollstream.js)
* `goog.net.WebSocket` - If Web Sockets are supported, use this.

`os.net.LongPoll` attempts to mimic the `goog.net.WebSocket` interface as much as possible. There may be other calls needed to setup/teardown streams depending on the remote server's API. If neither one of these options is supported (e.g. direct socket only), then it is not possible to connect from a web application.

Otherwise, as far as a plugin, it is the same as a Server or Data Provider plugin (enumerates the streams in the Add Data window, click them and they connect). The stream processing just converts to features and sticks them in a vector layer.
