### ISSUE TITLE
Areas aren't enabled on restart

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#879]
How to reproduce:
 - draw an area (I used box)
 - save area (Save Area... on Spatial menu - appears after lower right on draw), set title
 - note that new area is shown on Areas tab in Layers menu, and is enabled (ticked)
 - reload
 - note that new area is shown on Areas tab in Layers menu, but is no longer enabled
 - note that new area is not shown on map

I haven't dug far enough to work out if its not saved or not loaded (or both).

**Comment by gregroyal** [comment]
I believe this is by design to prevent infinite crashing on refresh. If you load too much data to the point the application crashes, on re-load it wont attempt to load the same data that crashed it.

Maybe if we can find a better way to address that issue, we can re-enable areas on refresh.

@wallw-bits  / @schmidtk

**Comment by schmidtk** [comment]
Greg is correct, this was by design. Given the temporal component to our queries, it isn't guaranteed (and quite unlikely in most of our users' cases) that the same data will be pulled each time the application is loaded. Even with the same filters/spatial queries, the temporal component will change the data volume.

If this behavior is added, I would recommend making it opt-in or something that can be configured on a layer-by-layer basis. For example, layers that do not require a spatial query to load are negatively impacted by this behavior. They will almost certainly load more data when the app is reloaded and query areas are disabled.

**Comment by bradh** [comment]
OK. I was treating the area as just being a named AOI, and using it to send to an upstream service that does my track filtering.

I'll find another way - perhaps a new layer. It was nice being able to use the existing drawing capabilities though.
